#  _    _ _   _           _                      _             _  
# | | _(_) |_| |_ _   _  | |_ ___ _ __ _ __ ___ (_)_ __   __ _| | 
# | |/ / | __| __| | | | | __/ _ \ '__| '_ ` _ \| | '_ \ / _` | | 
# |   <| | |_| |_| |_| | | ||  __/ |  | | | | | | | | | | (_| | | 
# |_|\_\_|\__|\__|\__, |  \__\___|_|  |_| |_| |_|_|_| |_|\__,_|_| 
#                 |___/              _          _   _             
#   ___ _   _ ___| |_ ___  _ __ ___ (_)______ _| |_(_) ___  _ __  
#  / __| | | / __| __/ _ \| '_ ` _ \| |_  / _` | __| |/ _ \| '_ \ 
# | (__| |_| \__ \ || (_) | | | | | | |/ / (_| | |_| | (_) | | | |
#  \___|\__,_|___/\__\___/|_| |_| |_|_/___\__,_|\__|_|\___/|_| |_|

##########################################################################

# https://www.reddit.com/r/KittyTerminal/comments/1dmpk30/need_a_decent_kittyconf_file/

# terminal opacity and blur
background_opacity 0.96
background_blur 6

# advance 
term xterm-kitty

# terminal bell
enable_audio_bell no

# os specific tweaks (Gnome window decoration for wayland)
# linux_display_server x11
macos_option_as_alt yes
macos_titlebar_color dark
macos_quit_when_last_window_closed yes

# font size management 
# map ctrl+shift+backspace change_font_size all 0

# cursor customization
# block / beam / underline
cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor

# scrollback
scrollback_lines 5000
wheel_scroll_multiplier 3.0

# mouse
mouse_hide_wait -1

# window layout
remember_window_size  no
initial_window_width  1200
initial_window_height 750
# window_border_width 1.5pt
# enabled_layouts tall
window_padding_width 0
window_margin_width 2
hide_window_decorations no

# window management 
# map ctrl+shift+enter new_window
# map ctrl+shift+] next_window
# map ctrl+shift+[ previous_window
map cmd+enter new_window_with_cwd

# layout management
map ctrl+shift+l next_layout
map ctrl+alt+r goto_layout tall
map ctrl+alt+s goto_layout stack
map command+z toggle_layout stack

map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter 3

# tab bar customization
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge top
tab_bar_align left
active_tab_font_style   bold
# inactive_tab_font_style normal

# tab management
# map ctrl+shift+t new_tab
# map ctrl+shift+right next_tab
# map ctrl+shift+left previous_tab
# map ctrl+shift+q close_tab


# BEGIN_KITTY_THEME
# Chalkboard
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="FiraMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
# END_KITTY_FONTS
